### ISSUE TITLE
Sørge for separat Github App for hver tenant

### ISSUE THREAD

**Issue by mortenlj** [nais/console#125]
I dag så bruker vi én felles Github App for console uavhengig av hvilken tenant det er.
Denne konfigurasjonen puttes inn i management clusteret slik at Console kan bruke den, men det betyr også at den strengt tatt er mulig å få tak i for de som er admins i en tenants google org ... som så kan benytte denne til å gjøre ting i en annen tenants github org.

Vi bør se om vi kan løse dette på en annen måte.

**Comment by christeredvartsen** [comment]
Will solve by creating a GitHub proxy for Console instead.

/cc @sechmann
