### ISSUE TITLE
Configure CNRM for team projects

### ISSUE THREAD

**Issue by mortenlj** [nais/console#35]
CNRM needs a service account in the team projects. This needs to be handled by Console when creating/updating the projects.

We need to do:
1. Create a service account for CNRM in each team project
2. Add workload identity permissions to the service account
3. Assign a role to the service account of the form `organizations/{org_id}/roles/CustomCNRMRole`

See how it's done in the old repo here:
https://github.com/nais/teams/blob/master/gcp-projects/modules/team-projects/main.tf#L52-L69

**Comment by christeredvartsen** [comment]
Fixed in 2757cc6d19afdc236716fcc3b0d09fd87f894ed4
