### ISSUE TITLE
Make it possible for admin to see when usersync last ran and other statistics

### ISSUE THREAD

**Issue by mortenlj** [nais/console#82]
When debugging missing users and related problems, knowing when the usersync last ran would be very useful.

Other metrics, such as how many users was synced etc. could also be useful to have visible in the frontend for global admin users.

**Comment by christeredvartsen** [comment]
Resolved by https://github.com/nais/console/pull/135 and https://github.com/nais/console-frontend/commit/4d43edd0d09830e6abaf54a43f495fa22829415c
